# fly.toml app configuration file generated for beyond-translation on 2023-09-05T16:08:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beyond-translation"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "heroku.dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[env]
  HEROKU_APP_NAME = "foo"
